language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mvdbeek
  password:
    secure: kZQvL+eEb01TyJNrXDJ+EmTyoXvTz3XPEzYYA9IHV0JNlIisVFVVcecLAPUcNjsnsMSnS2DH+9jmhZIPmsFCZIT4Q/b5eordvn9UMVgvfx4NHFSIz7ST9oJ7y2BnQALbCEHWyshzoS7FEmC9raKbgvp9wrYtDjVuofsGmnR/EzulNdif7xz0kyHrQTGfNi0Ci3HOIgkvZpKt1voOk+MVoVbBMkNBGMhX/h1JrOAJfQmi5YnY3bcFYFk78U3363oN8iE7jzeBaCinlbra9/ozX8Dq9HwQf/vAgM5HOIozGQo7qOAaz1H3tNTEV7LNXMmvHIxe2Mr2HenjUv2zKHIa9Iojr5bx4ftRS+H/MaA23k+RbNrJ0Rc0tjQljgZV/oTZjHkKtJGzdFX1T1DgpjElpDoxAeQ0AjU4aESeY9Z3q2XFd+Dyva9B1bQGJUXyzX64Eh9SdY1UatwMgG5RUfLXuuw2ayoLtGCPCSCa4jQjcEaGz24DbixE/35t8s/DAdaNWlIMzwk3Z81KOJ3f0061P2xOjkO5c7Xhl1yVvz6VW2FUEQGAtEuV8WLVaEG2dyu2+ZecW7/+ZwSvXAFt1/9fw2el3mp8WgO3rNC7fxNHhzHEcu5uvZoSfQX//Uia2K77g6HNg+P6zW5TSgkcwSSIqpHj+f9lMyBLDDibyXNK7M8=
  on:
    tags: true
    repo: mvdbeek/seaplotlib
    python: 3.6
