black = {
    'axes.facecolor': 'black',
    'axes.edgecolor': 'black',
    'axes.grid': False,
    'axes.axisbelow': True,
    'axes.labelcolor': 'white',
    'figure.facecolor': 'black',
    'grid.color': 'white',
    'grid.linestyle': '-',
    'text.color': 'white',
    'xtick.color': 'white',
    'ytick.color': 'white',
    'xtick.direction': 'out',
    'ytick.direction': 'out',
    'lines.solid_capstyle': 'round',
    'patch.edgecolor': 'w',
    'image.cmap': 'rocket',
    'font.family': ['sans-serif'],
    'font.sans-serif': ['Arial',
                        'DejaVu Sans',
                        'Liberation Sans',
                        'Bitstream Vera Sans',
                        'sans-serif'],
    'patch.force_edgecolor': True,
    'xtick.bottom': False,
    'xtick.top': False,
    'ytick.left': False,
    'ytick.right': False,
    'axes.spines.left': True,
    'axes.spines.bottom': True,
    'axes.spines.right': True,
    'axes.spines.top': True}

styles = {'black': black}
